### ISSUE TITLE
See response headers

### ISSUE THREAD

**Issue by IonicaBizau** [izuzak/urlreq#4]
Is there any way to see the response headers?

e.g.

``` sh
Cache-Control:no-cache, private
Content-Encoding:gzip
Content-Security-Policy:default-src *; script-src assets-cdn.github.com ...
Content-Type:text/html; charset=utf-8
Date:Mon, 22 Dec 2014 19:17:22 GMT
Server:GitHub.com
Status:200 OK
Strict-Transport-Security:max-age=31536000; includeSubdomains; preload
Transfer-Encoding:chunked
Vary:Accept-Encoding
Vary:X-PJAX
X-Content-Type-Options:nosniff
X-Frame-Options:deny
X-GitHub-Request-Id:4F7507....E40
X-Rack-Cache:miss
X-Request-Id:2c75b01c2..........e445
X-Runtime:0.006865
X-Served-By:bc4c....da31c
X-UA-Compatible:IE=Edge,chrome=1
X-XSS-Protection:1; mode=block
```

**Comment by izuzak** [comment]
You can see response headers in debug mode:

http://urlreq.appspot.com/req?method=POST&url=https%3A%2F%2Fapi.github.com%2Fmarkdown%2Fraw&Content-Type=text%2Fplain&body=**Hello**%20_World_!&debugMode=1

Is that what you mean?

**Comment by IonicaBizau** [comment]
Yes! Exactly! :smile: 

I'm using this tool for fixing https://github.com/IonicaBizau/IsRespo/issues/3.

**Comment by IonicaBizau** [comment]
Thanks a lot, [it's working](https://github.com/IonicaBizau/IsRespo/commit/d3c9a075589373f88f4d7d346d34ed8c13eda117#diff-ece786b9e8fb32d5d6c313d08a1c1db8R29)! :+1:
