### ISSUE TITLE
Service urlreq.appspot.com is under 'over quota'

### ISSUE THREAD

**Issue by hayorov** [izuzak/urlreq#7]
Hello, as for now http://urlreq.appspot.com/ is under 'over quota'.

**Comment by mavaras** [comment]
Same for me

**Comment by mavaras** [comment]
What would be a solution to this?

**Comment by rushiranpise** [comment]
I have the same error

**Comment by hayorov** [comment]
The solution is obviously to run a personal copy of the server. I got 300 bucks credit from GCP and run my own copy of URL Req. 8 years later .. it works fine. 

The quota limit happens from time to time, I guess the project in Appengine just hits the limit and/or somebody abuses the service.
